version: "3.1"

services:

  clickhouse_server:
    image: yandex/clickhouse-server
    ports:
      - ${CLICKHOUSE_SERVER_PORT}:${CLICKHOUSE_SERVER_PORT}
      - ${CLICKHOUSE_CLIENT_PORT}:${CLICKHOUSE_CLIENT_PORT}
    volumes:
      - clickhouse_volume:/var/lib/clickhouse
    networks:
      - clickhouse_network

  clickhouse_client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    networks:
      - clickhouse_network

volumes:
  clickhouse_volume:


networks:
  clickhouse_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.1.0/24
