version: '3.5'
services:
  zookeeper-ch:
    image: zookeeper:3.7
    container_name: zookeeper-ch
    hostname: zookeeper
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10

  clickhouse01:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "127.0.0.1:${CLICKHOUSE_HTTP_PORT}:${CLICKHOUSE_HTTP_PORT}"
      - "127.0.0.1:${CLICKHOUSE_CLIENT_PORT}:${CLICKHOUSE_CLIENT_PORT}"
    env_file:
      - .env
    volumes:
      - ${PWD}/clickhouse/clickhouse01:/etc/clickhouse-server
    depends_on:
      - zookeeper-ch

  clickhouse02:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    volumes:
      - ${PWD}/clickhouse/clickhouse02:/etc/clickhouse-server
    depends_on:
      - zookeeper-ch

  waiter:
    image: busybox
    container_name: waiter-container
    volumes:
      - ./wait_for_it.sh:/wait_for_it.sh
    command: sh /wait_for_it.sh
    env_file:
      - .env
    networks:
      - clickhouse-network
    depends_on:
      - clickhouse01
      - clickhouse02

  etl:
    build:
      context: .
    container_name: etl-kafka-ch
    env_file:
      - .env
    networks:
      - clickhouse-network
    depends_on:
      - waiter      
    
networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24

